export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  CART_NOT_FOUND: "CART_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  COUPON_NOT_FOUND: "COUPON_NOT_FOUND",
  ITEM_NOT_IN_CART: "ITEM_NOT_IN_CART",
  INSUFFICIENT_INVENTORY: "INSUFFICIENT_INVENTORY",
  ITEM_ALREADY_IN_CART: "ITEM_ALREADY_IN_CART",
  CART_ALREADY_CHECKED_OUT: "CART_ALREADY_CHECKED_OUT",
  CART_EMPTY: "CART_EMPTY",
  COUPON_UNAVAILABLE: "COUPON_UNAVAILABLE",
  NO_ELIGIBLE_MILESTONE: "NO_ELIGIBLE_MILESTONE",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  COUPON_CODE_TAKEN: "COUPON_CODE_TAKEN",
  COUPON_LOCKED: "COUPON_LOCKED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export type DomainError = {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
};

export function domainError(
  code: ErrorCode,
  message: string,
  details?: Record<string, unknown>,
): DomainError {
  return details === undefined ? { code, message } : { code, message, details };
}
